[package]
name = "cqdb"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jhash = "0.1.1"
libc = "0.2.82"

[dev-dependencies]
cqdb-sys = "0.1.0"
libc = "0.2.82"
