[package]
name = "cqdb"
version = "0.2.0"
authors = ["messense <messense@icloud.com>"]
description = "Rust implementation of Constant Quark Database (CQDB)"
edition = "2018"
license = "MIT"
repository = "https://github.com/messense/cqdb-rs"
keywords = ["cdb", "cqdb", "crfsuite"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.1.3"
bitflags = "1.2.1"
jhash = "0.1.1"

[dev-dependencies]
cqdb-sys = "0.1.0"
libc = "0.2.82"

[workspace]
members = [
    ".",
    "ffi"
]